name: CI for k6 tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  k6-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          #sudoapt-get install -y k6

          sudo apt-get update
          sudo apt-get install -y ca-certificates gnupg curl
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/etc/apt/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6
      - name: Run smoke test
        run: |
          k6 run tests/smoke.js

      - name: Run load test
        run: |
          k6 run tests/load.js
