name: CI for k6 tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  k6-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run smoke test
        run: |
          k6 run tests/smoke.js

      - name: Run load test
        run: |
          k6 run tests/load.js
